# Generated by Django 2.2 on 2021-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Books'),
        ),
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Books_Authors',
        ),
    ]
